### ISSUE TITLE
Constellations cannot be printed

### ISSUE THREAD

**Issue by papojari** [Haruno19/starfetch#10]
I installed with `sudo make install`
However I get
```
➜ /usr/local/bin/starfetch        
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::replace: __pos (which is 18446744073709551615) > this->size() (which is 723)
zsh: IOT instruction (core dumped)  /usr/local/bin/starfetch
```
or

```
✗ /usr/local/bin/starfetch -n orion
Error: the constellation you asked for isn't recognized.

starfetch is a command line tool that displays information about a constellation alongside its scheme.

Usage: starfetch [OPTION] [CONSTELLATION NAME]
    -h      Prints this help message.
    -n      Shows the selected constellation.
    -r      Shows a random constellation.
    -l      Prints the list of all the available constellations.
    
If launched with no arguments, the behaviour is the same as with '-r'.

Examples:   starfetch -r
            starfetch -n orion
            starfetch
```

**Comment by Haruno19** [comment]
That's weird.
Could you please post the output of `ls /usr/local/starfetch/res/constellations/`?

**Comment by papojari** [comment]
```
➜ ls /usr/local/starfetch/res/constellations/
antlia.json    aries.json      cassiopeia.json	    gemini.json  ophiuchus.json    scorpio.json     virgo.json
apus.json      bootes.json     corona_borealis.json  leo.json	 orion.json	   taurus.json
aquarius.json  cancer.json     crux.json	    libra.json   pisces.json	   ursa_major.json
ara.json       capricorn.json  cygnus.json	    lupus.json   sagittarius.json  ursa_minor.json
```

**Comment by Haruno19** [comment]
I'm not able to replicate this bug; I tried on both MacOS and (Arch) Linux, and it worked as expected.
Therefore, if possible, I need to investigate on this issue directly on your environment. 

It looks like either the `path` or `pathc` variables do not assume the expected value, resulting in starfetch not finding the .json files path. In order to verify this, could you please replace `src/starfetch.cpp` with [this version](https://drive.google.com/file/d/131aHTdlSJJKCLIgYnRV4k3RzEc9Ne-0p/view?usp=sharing) (or just add a print statement like `cout << pathc << endl;` somewhere around line 60 of `src/starfetch.cpp`), re-install it and run again `/usr/bin/starfetch -n orion` please?

Thank you for your cooperation.

**Comment by Haruno19** [comment]
Upon further examination, considering the output of `/usr/local/bin/starfetch` it looks like `string::find` isn't able to find the placeholder characters (`%0` and such) in the variable `s` (therefore the `__pos` value passed to `basic_string::replace` is very high, `18446744073709551615`). 

This means that somehow `/usr/local/starfetch/res/templace` doesn't get opened properly, resulting in the string `s` being empty. And this makes perfectly sense if the problem is actually due to the string `path` not being assigned correctly. 
What doesn't make sense to me, is that `basic_string::replace` is called only if the file `c`, with path `pathc`, has been opened correctly, which should be impossible since the variable `path` should be wrong to begin with. 

Knowing what the `path` or `pathc` contain during execution will probably help solving this mystery.

**Comment by papojari** [comment]
> I'm not able to replicate this bug; I tried on both MacOS and (Arch) Linux, and it worked as expected. Therefore, if possible, I need to investigate on this issue directly on your environment.
> 
> It looks like either the `path` or `pathc` variables do not assume the expected value, resulting in starfetch not finding the .json files path. In order to verify this, could you please replace `src/starfetch.cpp` with [this version](https://drive.google.com/file/d/131aHTdlSJJKCLIgYnRV4k3RzEc9Ne-0p/view?usp=sharing) (or just add a print statement like `cout << pathc << endl;` somewhere around line 60 of `src/starfetch.cpp`), re-install it and run again `/usr/bin/starfetch -n orion` please?
> 
> Thank you for your cooperation.

```
➜ /usr/local/bin/starfetch -n orion
Error: the constellation you asked for isn't recognized.

starfetch is a command line tool that displays information about a constellation alongside its scheme.

Usage: starfetch [OPTION] [CONSTELLATION NAME]
    -h      Prints this help message.
    -n      Shows the selected constellation.
    -r      Shows a random constellation.
    -l      Prints the list of all the available constellations.
    
If launched with no arguments, the behaviour is the same as with '-r'.

Examples:   starfetch -r
            starfetch -n orion
            starfetch
            ```
            still the same

**Comment by papojari** [comment]
I guess this has to do with NixOS?

**Comment by papojari** [comment]
There is no `/usr/local/starfetch/res/template` on my machine

**Comment by Haruno19** [comment]
Uh? There's no `template` file under the `res` folder? 
That's definitely what's causing this problem. 

The makefile does this: `cp -rf ./res ${INSTALL_DIR}/starfetch/`, which copies the whole `res` folder into `/usr/local/starfetch/`, and the `template` file is inside that.

Can you please check if `starfetch/res/template` is present when you extract `starfetch.tar.gz`? It definitely is contained in the archive.

**Comment by Haruno19** [comment]
I don't know if it has to do with the fact that the `template` file has no extension, but I find it really weird?
If that's the case, I can fix this easily by giving it an extension and change the code accordingly, but it shouldn't be needed.

**Comment by papojari** [comment]
Umm… so originally I did `git pull` to update and got this issue. I now deleted the repo folder and cloned it again - issue solved :facepalm:
