### ISSUE TITLE
Weird folder name for constellations

### ISSUE THREAD

**Issue by papojari** [Haruno19/starfetch#2]
Why are the does `make install` store the star constellations in `/usr/local/starfetch/res/constellations/` and not in `/usr/share/starfetch/constellations/` e.g.?

**Comment by Haruno19** [comment]
Hi, thank you for opening this issue. 
That's the expected behaviour, the star constellations file are resource files, and the program expects them to be located in `usr/local/starfetch/res/constellations/`. It's purely a design choice, in order to have every resource file stored in the same folder, `/res`.

**Comment by papojari** [comment]
Ok I guess. I had never seen this folder.
